sudo: required
services:
  - docker

before_install:
  - docker build -t angaria3/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true angaria3/react-test npm test -- --coverage

after-success:
  - docker build -t angaria3/multi-client ./client
  - docker build -t angaria3/multi-nginx ./nginx
  - docker build -t angaria3/multi-server ./server
  - docker build -t angaria3/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push angaria3/multi-client
  - docker push angaria3/multi-nginx
  - docker push angaria3/multi-server
  - docker push angaria3/multi-worker
  
  